### ISSUE TITLE
exceptions.enable() not sending events?

### ISSUE THREAD

**Issue by zooba** [Microsoft/AppInsights-Python#8]
I've been trying the unhandled exception filter and it doesn't seem to be sending events.

My code is roughly:
```
>>> from applicationinsights.exceptions import enable
>>> enable("my-key-goes-here")
>>> 1 / 0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: division by zero
```

There's a visible pause before the exception message appears, which I assume is the flush() call in the handler, but the messages never appear in the portal. (Adding trace messages also shows that the handler is being called, but I didn't look any deeper than that.)

By contrast, if I create a client with the same key and call `tc.track_exception()` within an except block, the message appears in the portal in less than a minute.

(Using Python 3.4.2)

**Comment by BogdanBe** [comment]
I've tried the sample code above (with an actual key instead of the placeholder) and could not repro the issue. Here is what I'm seeing:

*The code*
![00_ide](https://cloud.githubusercontent.com/assets/9849850/5830685/0dc59352-a0d9-11e4-8906-ee2bac708f93.png)

*Fiddler trace of the request (endpoint accepted the message)*
![01_fiddler](https://cloud.githubusercontent.com/assets/9849850/5830655/a402f9be-a0d8-11e4-9b90-7afb1beab558.png)

*The UI about a minute later*
![02_browser](https://cloud.githubusercontent.com/assets/9849850/5830656/a403a094-a0d8-11e4-94d4-be5ca6d5b87f.png)

The `flush()` does seem to cause a pause; we'll have to investigate why exactly that is, but as for the `enable()` method, it seems to be working as intended.

**Comment by zooba** [comment]
I think `flush()` causing a pause is fine - the process is about to terminate and the send needs to complete.

It seems to be fine now, so maybe the service was having its own issues at the time I was trying it.
